# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('telegram_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_id',
            field=models.BigIntegerField(verbose_name='Message Id'),
        ),
    ]
