# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 09:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('telegram_API', '0002_auto_20170104_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='extra_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Extra Fields'),
        ),
    ]
