# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 13:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_API', '0003_auto_20170105_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edit_date',
            field=models.DateTimeField(null=True, verbose_name='Edit Date'),
        ),
        migrations.AddField(
            model_name='message',
            name='entities',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Entities'),
        ),
        migrations.AddField(
            model_name='message',
            name='forward_date',
            field=models.DateTimeField(null=True, verbose_name='Forward Date'),
        ),
        migrations.AddField(
            model_name='message',
            name='forward_from_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_messages', to='telegram_API.Chat', verbose_name='Forward From Chat'),
        ),
        migrations.AlterField(
            model_name='update',
            name='update_type',
            field=models.CharField(choices=[('message', 'Message'), ('channel_post', 'Channel Post'), ('message', 'Edited Message'), ('channel_post', 'Edited Channel Post')], default='message', max_length=20, verbose_name='Update Type'),
        ),
    ]
