# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_API', '0004_auto_20170106_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edit Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Forward Date'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_from_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_messages', to='telegram_API.Chat', verbose_name='Forward From Chat'),
        ),
    ]
