# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import foward_bot.fowarder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_API', '0002_auto_20170104_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Status')),
                ('lang', models.CharField(choices=[(b'ar', b'ARABIC'), (b'zh', b'CHINESE'), (b'en', b'ENGLISH'), (b'fr', b'FRENCH'), (b'None', b'NONE'), (b'ru', b'RUSSIAN'), (b'es', b'SPANISH')], default=foward_bot.fowarder.models.Languages('None'), max_length=4, verbose_name='Language')),
                ('forwarder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarder', to='telegram_API.Chat', verbose_name='Forwarder')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='telegram_API.Chat', verbose_name='Receiver')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='autoforward',
            unique_together=set([('forwarder', 'receiver')]),
        ),
    ]
