# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_API', '0003_auto_20170105_0927'),
        ('fowarder', '0002_auto_20170104_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoforward',
            name='creator',
            field=models.ForeignKey(default=116426384, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='telegram_API.User', verbose_name='Forwarding Creator'),
            preserve_default=False,
        ),
    ]
