# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fowarder', '0005_auto_20170110_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoforward',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
